-- shared/actions.lua — catálogo declarativo das intenções administrativas

VHubAdmin = VHubAdmin or {}

VHubAdmin.ACTIONS = {
  -- MODERAÇÃO
  kick = { perm = 'kick', cat = 'moderation', label = 'Expulsar',
    desc = 'Remove um jogador conectado.', fields = { 'target', 'reason' } },
  ban = { perm = 'ban', cat = 'moderation', label = 'Banir', dangerous = true,
    desc = 'Bane pelo UID do alvo conectado.', fields = { 'target', 'reason' } },
  unban = { perm = 'unban', cat = 'moderation', label = 'Desbanir',
    desc = 'Remove um banimento pelo UID.', fields = { 'uid' } },
  warn = { perm = 'warn', cat = 'moderation', label = 'Avisar',
    desc = 'Envia um aviso auditado.', fields = { 'target', 'message' } },
  jail = { perm = 'jail', cat = 'moderation', label = 'Prender', dangerous = true,
    desc = 'Prisão persistente e aplicada pelo servidor.', fields = { 'target', 'minutes', 'reason' } },
  unjail = { perm = 'jail', cat = 'moderation', label = 'Soltar',
    desc = 'Libera uma prisão ativa.', fields = { 'target' } },
  mute = { perm = 'mute', cat = 'moderation', label = 'Silenciar',
    desc = 'Bloqueia chat no servidor.', fields = { 'target', 'minutes', 'reason' } },
  unmute = { perm = 'mute', cat = 'moderation', label = 'Liberar fala',
    desc = 'Remove o bloqueio de chat.', fields = { 'target' } },

  -- DESLOCAMENTO
  tp = { perm = 'tp', cat = 'teleport', label = 'Ir até jogador',
    desc = 'Teleporta pelo owner do ped.', fields = { 'target' } },
  tptome = { perm = 'bring', cat = 'teleport', label = 'Trazer jogador',
    desc = 'Traz o alvo para sua posição.', fields = { 'target' } },
  tpgo = { perm = 'tpgo', cat = 'teleport', label = 'Ir ao marcador',
    desc = 'Resolve o waypoint e valida no servidor.', fields = {} },
  tpcds = { perm = 'tpcds', cat = 'teleport', label = 'Ir a coordenadas',
    desc = 'Coordenadas validadas antes do teleporte.', fields = { 'x', 'y', 'z', 'h' } },
  tpall = { perm = 'tpall', cat = 'teleport', label = 'Trazer todos', dangerous = true,
    desc = 'Move todos os jogadores conectados.', fields = {} },
  tplast = { perm = 'tp', cat = 'teleport', label = 'Voltar',
    desc = 'Retorna à última posição registrada pelo painel.', fields = {} },
  tpz = { perm = 'tp', cat = 'teleport', label = 'Ir a destino',
    desc = 'Escolhe um destino curado pelo servidor.', fields = { 'zone' } },

  -- PESSOAS
  heal = { perm = 'heal', cat = 'player', label = 'Curar',
    desc = 'Restaura vida e colete pelo owner do ped.', fields = { 'target' } },
  healall = { perm = 'heal', cat = 'player', label = 'Curar todos', dangerous = true,
    desc = 'Restaura vida e colete de todos.', fields = {} },
  god = { perm = 'god', cat = 'player', label = 'Invencibilidade',
    desc = 'Alterna invencibilidade própria.', fields = {} },
  noclip = { perm = 'noclip', cat = 'player', label = 'Modo livre',
    desc = 'Alterna noclip próprio.', fields = {} },
  freeze = { perm = 'freeze', cat = 'player', label = 'Congelar',
    desc = 'Alterna congelamento do alvo.', fields = { 'target' } },
  revive = { perm = 'revive', cat = 'player', label = 'Reviver',
    desc = 'Revive pelo owner do estado do jogador.', fields = { 'target' } },
  reviveall = { perm = 'revive', cat = 'player', label = 'Reviver todos', dangerous = true,
    desc = 'Revive todos os jogadores.', fields = {} },
  invis = { perm = 'invisible', cat = 'player', label = 'Invisibilidade',
    desc = 'Alterna invisibilidade própria.', fields = {} },
  spec = { perm = 'spec', cat = 'player', label = 'Espectar',
    desc = 'Alterna espectador do alvo.', fields = { 'target' } },
  skin = { perm = 'skin', cat = 'player', label = 'Skin (PedHash)',
    desc = 'Altera modelo do personagem pelo dono de ped.', fields = { 'target', 'model' } },
  kill = { perm = 'god', cat = 'player', label = 'Matar', dangerous = true,
    desc = 'Derruba a vida do alvo a zero.', fields = { 'target' } },
  stamina = { perm = 'buff', cat = 'player', label = 'Stamina infinita',
    desc = 'Alterna stamina própria.', fields = {} },
  jump = { perm = 'buff', cat = 'player', label = 'Super pulo',
    desc = 'Alterna super pulo próprio.', fields = {} },
  cleanped = { perm = 'heal', cat = 'player', label = 'Limpar personagem',
    desc = 'Remove sangue e sujeira próprios.', fields = {} },

  -- VEICULO EFEMERO
  spawncar = { perm = 'vehicle_spawn', cat = 'vehicle', label = 'Criar veículo',
    desc = 'Cria um veículo local validado.', fields = { 'model' } },
  delveh = { perm = 'vehicle_delete', cat = 'vehicle', label = 'Remover veículo', dangerous = true,
    desc = 'Remove o veículo administrativo atual.', fields = {} },
  fix = { perm = 'vehicle_fix', cat = 'vehicle', label = 'Reparar veículo',
    desc = 'Repara o veículo atual.', fields = {} },
  boost = { perm = 'vehicle_boost', cat = 'vehicle', label = 'Boost de motor',
    desc = 'Aplica potência temporária validada.', fields = {} },
  flip = { perm = 'vehicle_fix', cat = 'vehicle', label = 'Desvirar veículo',
    desc = 'Reposiciona o veículo atual sobre as rodas.', fields = {} },
  tuning = { perm = 'vehicle_fix', cat = 'vehicle', label = 'Tuning completo',
    desc = 'Aplica tuning ao veículo atual.', fields = {} },
  carcolor = { perm = 'vehicle_fix', cat = 'vehicle', label = 'Cor do veículo',
    desc = 'Altera a cor principal e secundária.', fields = { 'color' } },

  -- FROTA PERSISTENTE — o vhub_garage é o dono de cada mutação.
  fleetGive = { perm = 'vehicle_manage', cat = 'fleet', label = 'Conceder veículo',
    desc = 'Cria veículo persistente para o personagem do alvo.', fields = { 'target', 'model', 'plate' } },
  fleetTransfer = { perm = 'vehicle_manage', cat = 'fleet', label = 'Transferir posse', dangerous = true,
    desc = 'Transfere placa persistente pelo contrato da garagem.', fields = { 'plate', 'target' } },
  fleetDelete = { perm = 'vehicle_manage', cat = 'fleet', label = 'Excluir veículo', dangerous = true,
    desc = 'Remove registro, chaves e entidade da placa.', fields = { 'plate' } },
  fleetStatus = { perm = 'vehicle_manage', cat = 'fleet', label = 'Definir status',
    desc = 'Altera o status canônico da placa.', fields = { 'plate', 'status' } },
  fleetIpva = { perm = 'vehicle_manage', cat = 'fleet', label = 'Renovar IPVA',
    desc = 'Renova por dias a partir do vencimento atual.', fields = { 'plate', 'days' } },
  fleetRelease = { perm = 'vehicle_manage', cat = 'fleet', label = 'Liberar pátio',
    desc = 'Libera uma placa apreendida.', fields = { 'plate' } },
  fleetGrantKey = { perm = 'vehicle_manage', cat = 'fleet', label = 'Conceder chave',
    desc = 'Concede uma chave ao personagem do alvo.', fields = { 'plate', 'target', 'days' } },
  fleetRevokeKey = { perm = 'vehicle_manage', cat = 'fleet', label = 'Revogar chave', dangerous = true,
    desc = 'Revoga a chave da placa para o alvo.', fields = { 'plate', 'target' } },
  fleetDespawn = { perm = 'vehicle_manage', cat = 'fleet', label = 'Recolher placa',
    desc = 'Despawna a placa no servidor.', fields = { 'plate' } },
  fleetPurgeKeys = { perm = 'vehicle_manage', cat = 'fleet', label = 'Limpar chaves vencidas', dangerous = true,
    desc = 'Remove autorizações expiradas.', fields = {} },
  fleetPurgeLogs = { perm = 'vehicle_manage', cat = 'fleet', label = 'Limpar logs antigos', dangerous = true,
    desc = 'Remove logs da frota por retenção.', fields = { 'days' } },
  fleetFinalizeAuctions = { perm = 'vehicle_manage', cat = 'fleet', label = 'Finalizar leilões vencidos', dangerous = true,
    desc = 'Processa leilões vencidos pelo dono.', fields = {} },

  -- MUNDO
  weather = { perm = 'weather', cat = 'world', label = 'Clima',
    desc = 'Define clima replicado por GlobalState.', fields = { 'weather' } },
  time = { perm = 'time', cat = 'world', label = 'Horário',
    desc = 'Define hora e minuto globais.', fields = { 'hour', 'minute' } },
  blackout = { perm = 'blackout', cat = 'world', label = 'Apagão', dangerous = true,
    desc = 'Alterna luz artificial global.', fields = { 'on' } },
  announce = { perm = 'announce', cat = 'world', label = 'Anunciar',
    desc = 'Emite anúncio global.', fields = { 'message' } },
  staffchat = { perm = 'staffchat', cat = 'world', label = 'Equipe',
    desc = 'Envia mensagem à equipe online.', fields = { 'message' } },
  clearzone = { perm = 'clearzone', cat = 'world', label = 'Limpar área', dangerous = true,
    desc = 'Limpa efeitos locais em torno do administrador.', fields = { 'radius' } },
  wipeveh = { perm = 'wipe', cat = 'world', label = 'Limpar veículos vazios', dangerous = true,
    desc = 'Remove entidades desocupadas no servidor.', fields = {} },
  wipeped = { perm = 'wipe', cat = 'world', label = 'Limpar NPCs', dangerous = true,
    desc = 'Remove NPCs no servidor.', fields = {} },
  wipeobj = { perm = 'wipe', cat = 'world', label = 'Limpar objetos', dangerous = true,
    desc = 'Remove objetos no servidor.', fields = {} },

  -- DELEGAÇÕES AOS DONOS ECONÔMICOS
  givemoney = { perm = 'givemoney', cat = 'economy', label = 'Dar dinheiro',
    desc = 'Credita pelo contrato do banco.', fields = { 'target', 'amount', 'rota', 'reason' } },
  removemoney = { perm = 'givemoney', cat = 'economy', label = 'Remover dinheiro', dangerous = true,
    desc = 'Debita pelo contrato do banco.', fields = { 'target', 'amount', 'rota', 'reason' } },
  setmoney = { perm = 'setmoney', cat = 'economy', label = 'Definir saldo', dangerous = true,
    desc = 'Define saldo pelo contrato do banco.', fields = { 'target', 'amount', 'rota', 'reason' } },
  giveitem = { perm = 'giveitem', cat = 'inventory', label = 'Dar item',
    desc = 'Entrega item validado pelo inventário.', fields = { 'target', 'item', 'qty', 'reason' } },
  addgroup = { perm = 'addgroup', cat = 'groups', label = 'Adicionar grupo',
    desc = 'Concede grupo pelo owner de permissões.', fields = { 'target', 'group', 'level', 'days', 'reason' } },
  delgroup = { perm = 'delgroup', cat = 'groups', label = 'Remover grupo', dangerous = true,
    desc = 'Remove grupo pelo owner de permissões.', fields = { 'target', 'group', 'reason' } },
}
