-- shared/config.lua — catálogo de emotes e regras de bloqueio do vhub_animacao

VHubAnimacao = VHubAnimacao or {}
VHubAnimacao.Cfg = {}


-- ============================================================
-- CONJUNTOS DE REGRAS
-- ============================================================

-- Emotes bloqueados quando o player está com arma sacada (vantagem de combate).
VHubAnimacao.Cfg.ADVANTAGE = {
    deitar   = true, deitar2  = true, deitar3  = true, deitar4  = true,
    deitar5  = true, deitar6  = true, deitar7  = true, deitar8  = true,
    rastejar = true, ajoelhar = true, debrucar = true,
    dormir   = true, dormir2  = true, dormir3  = true, dormir4  = true, dormir5  = true,
}

-- Emotes que envolvem interação física com outro player (futura implementação de consentimento).
VHubAnimacao.Cfg.CONSENT = {
    beijar = true, abracar = true, abracar2 = true,
}


-- ============================================================
-- CATÁLOGO RAW (array → convertido para MAP ao final)
-- Campos: dict?, anim, prop?, flag?, hand?, loop?, andar?, carros?
--   Sem dict + anim presente  → TaskStartScenarioInPlace
--   Sem dict + sem anim       → apenas anexar prop (prop-only)
--   Com dict                  → TaskPlayAnim (+ anexar prop se houver)
-- ============================================================

local _raw = {

    -- MILITARES
    { nome = "riflerelax"  , dict = "anim@fog_rifle_relaxed"                     , anim = "rifle_relaxed_clip"     , loop = true  , andar = false },
    { nome = "stack1"      , dict = "anim@stack_pointman"                         , anim = "pointman_clip"          , loop = true  , andar = false },
    { nome = "stack2"      , dict = "anim@stack_two_man"                          , anim = "two_man_clip"           , loop = true  , andar = false },
    { nome = "stack3"      , dict = "anim@stack_three_man"                        , anim = "three_man_clip"         , loop = true  , andar = false },
    { nome = "highlow1"    , dict = "anim@highlow_low_lean"                       , anim = "low_lean_clip"          , loop = true  , andar = false },
    { nome = "highlow2"    , dict = "anim@highlow_high_lean"                      , anim = "high_lean_clip"         , loop = true  , andar = false },
    { nome = "highlow3"    , dict = "anim@tactical_highlow_high_leftlean"         , anim = "high_leftlean_clip"     , loop = true  , andar = false },
    { nome = "highlow4"    , dict = "anim@tactical_highlow_low_leftlean"          , anim = "low_leftlean_clip"      , loop = true  , andar = false },
    { nome = "kneeltalkie" , dict = "anim@tactical_kneel_walkie"                  , anim = "kneel_walkie_clip"      , loop = true  , andar = false },
    { nome = "aimkneel"    , dict = "anim@tactical_kneel_aiming"                  , anim = "kneel_aiming_clip"      , loop = true  , andar = false },
    { nome = "riflerelax1" , dict = "anim@male_tactical_collapsed_lowready"       , anim = "collapsed_lowready_clip", loop = true  , andar = false },
    { nome = "riflerelax2" , dict = "anim@male_tactical_highready_relaxed"        , anim = "highready_relaxed_clip" , loop = true  , andar = false },

    -- PROP-ONLY (sem animação; apenas anexar objeto)
    { nome = "radio2" , prop = "prop_boombox_01"       , flag = 50 , hand = 57005 },
    { nome = "bolsa"  , prop = "prop_ld_case_01"       , flag = 50 , hand = 57005 },
    { nome = "bolsa2" , prop = "prop_ld_case_01_s"     , flag = 50 , hand = 57005 },
    { nome = "bolsa3" , prop = "prop_security_case_01" , flag = 50 , hand = 57005 },
    { nome = "bolsa4" , prop = "w_am_case"             , flag = 50 , hand = 57005 },
    { nome = "caixa2" , prop = "prop_tool_box_04"      , flag = 50 , hand = 57005 },
    { nome = "lixo"   , prop = "prop_cs_rub_binbag_01" , flag = 50 , hand = 57005 },
    { nome = "mic"    , prop = "prop_microphone_02"    , flag = 50 , hand = 60309 },
    { nome = "mic2"   , prop = "p_ing_microphonel_01"  , flag = 50 , hand = 60309 },
    { nome = "buque"  , prop = "prop_snow_flower_02"   , flag = 50 , hand = 60309 },
    { nome = "rosa"   , prop = "prop_single_rose"      , flag = 50 , hand = 60309 },

    -- PROP + ANIMAÇÃO
    { nome = "mic3"      , dict = "missfra1"                                          , anim = "mcs2_crew_idle_m_boom"         , prop = "prop_v_bmike_01"      , flag = 50 , hand = 28422 },
    { nome = "prebeber"  , dict = "amb@code_human_wander_drinking@beer@male@base"     , anim = "static"                        , prop = "prop_fib_coffee"      , flag = 49 , hand = 28422 },
    { nome = "prebeber2" , dict = "amb@code_human_wander_drinking@beer@male@base"     , anim = "static"                        , prop = "prop_ld_flow_bottle"  , flag = 49 , hand = 28422 },
    { nome = "prebeber3" , dict = "amb@code_human_wander_drinking@beer@male@base"     , anim = "static"                        , prop = "prop_cs_bs_cup"       , flag = 49 , hand = 28422 },
    { nome = "sinalizar" , dict = "amb@world_human_car_park_attendant@male@base"      , anim = "base"                          , prop = "prop_parking_wand_01" , flag = 49 , hand = 28422 },
    { nome = "placa"     , dict = "amb@world_human_bum_freeway@male@base"             , anim = "base"                          , prop = "prop_beggers_sign_01" , flag = 49 , hand = 28422 },
    { nome = "placa2"    , dict = "amb@world_human_bum_freeway@male@base"             , anim = "base"                          , prop = "prop_beggers_sign_03" , flag = 49 , hand = 28422 },
    { nome = "placa3"    , dict = "amb@world_human_bum_freeway@male@base"             , anim = "base"                          , prop = "prop_beggers_sign_04" , flag = 49 , hand = 28422 },
    { nome = "ligar"     , dict = "cellphone@"                                        , anim = "cellphone_call_in"             , prop = "prop_amb_phone"       , flag = 50 , hand = 28422 },
    { nome = "radio"     , dict = "cellphone@"                                        , anim = "cellphone_call_in"             , prop = "prop_cs_hand_radio"   , flag = 50 , hand = 28422 },
    { nome = "cafe"      , dict = "amb@world_human_aa_coffee@base"                    , anim = "base"                          , prop = "prop_fib_coffee"      , flag = 50 , hand = 28422 },
    { nome = "cafe2"     , dict = "amb@world_human_aa_coffee@idle_a"                  , anim = "idle_a"                        , prop = "prop_fib_coffee"      , flag = 49 , hand = 28422 },
    { nome = "caixa"     , dict = "anim@heists@box_carry@"                            , anim = "idle"                          , prop = "hei_prop_heist_box"   , flag = 50 , hand = 28422 },
    { nome = "chuva"     , dict = "amb@world_human_drinking@coffee@male@base"         , anim = "base"                          , prop = "p_amb_brolly_01"      , flag = 50 , hand = 28422 },
    { nome = "chuva2"    , dict = "amb@world_human_drinking@coffee@male@base"         , anim = "base"                          , prop = "p_amb_brolly_01_s"    , flag = 50 , hand = 28422 },
    { nome = "comer"     , dict = "amb@code_human_wander_eating_donut@male@idle_a"    , anim = "idle_c"                        , prop = "prop_cs_burger_01"    , flag = 49 , hand = 28422 },
    { nome = "comer2"    , dict = "amb@code_human_wander_eating_donut@male@idle_a"    , anim = "idle_c"                        , prop = "prop_cs_hotdog_01"    , flag = 49 , hand = 28422 },
    { nome = "comer3"    , dict = "amb@code_human_wander_eating_donut@male@idle_a"    , anim = "idle_c"                        , prop = "prop_amb_donut"       , flag = 49 , hand = 28422 },
    { nome = "beber"     , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "p_cs_bottle_01"       , flag = 49 , hand = 28422 },
    { nome = "beber2"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "prop_energy_drink"    , flag = 49 , hand = 28422 },
    { nome = "beber3"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "prop_amb_beer_bottle" , flag = 49 , hand = 28422 },
    { nome = "beber4"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "p_whiskey_notop"      , flag = 49 , hand = 28422 },
    { nome = "beber5"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "prop_beer_logopen"    , flag = 49 , hand = 28422 },
    { nome = "beber6"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "prop_beer_blr"        , flag = 49 , hand = 28422 },
    { nome = "beber7"    , dict = "amb@world_human_drinking@beer@male@idle_a"         , anim = "idle_a"                        , prop = "prop_ld_flow_bottle"  , flag = 49 , hand = 28422 },
    { nome = "varrer"    , dict = "amb@world_human_janitor@male@idle_a"               , anim = "idle_a"                        , prop = "prop_tool_broom"      , flag = 49 , hand = 28422 },
    { nome = "musica"    , dict = "amb@world_human_musician@guitar@male@base"         , anim = "base"                          , prop = "prop_el_guitar_01"    , flag = 49 , hand = 60309 },
    { nome = "musica2"   , dict = "amb@world_human_musician@guitar@male@base"         , anim = "base"                          , prop = "prop_el_guitar_02"    , flag = 49 , hand = 60309 },
    { nome = "musica3"   , dict = "amb@world_human_musician@guitar@male@base"         , anim = "base"                          , prop = "prop_el_guitar_03"    , flag = 49 , hand = 60309 },
    { nome = "musica4"   , dict = "amb@world_human_musician@guitar@male@base"         , anim = "base"                          , prop = "prop_acc_guitar_01"   , flag = 49 , hand = 60309 },
    { nome = "camera"    , dict = "amb@world_human_paparazzi@male@base"               , anim = "base"                          , prop = "prop_pap_camera_01"   , flag = 49 , hand = 28422 },
    { nome = "camera2"   , dict = "missfinale_c2mcs_1"                                , anim = "fin_c2_mcs_1_camman"           , prop = "prop_v_cam_01"        , flag = 49 , hand = 28422 },
    { nome = "prancheta" , dict = "amb@world_human_clipboard@male@base"               , anim = "base"                          , prop = "p_amb_clipboard_01"   , flag = 50 , hand = 60309 },
    { nome = "mapa"      , dict = "amb@world_human_clipboard@male@base"               , anim = "base"                          , prop = "prop_tourist_map_01"  , flag = 50 , hand = 60309 },
    { nome = "anotar"    , dict = "amb@medic@standing@timeofdeath@base"               , anim = "base"                          , prop = "prop_notepad_01"      , flag = 49 , hand = 60309 },
    { nome = "anotar2"   , dict = "cellphone@"                                        , anim = "cellphone_text_in"             , prop = "prop_police_phone"    , flag = 50 , hand = 28422 },
    { nome = "britadeira", dict = "amb@world_human_const_drill@male@drill@base"       , anim = "base"                          , prop = "prop_tool_jackham"    , flag = 15 , hand = 28422 },
    { nome = "malhar"    , dict = "amb@world_human_muscle_free_weights@male@barbell@base", anim = "base"                       , prop = "prop_curl_bar_01"     , flag = 49 , hand = 28422 },
    { nome = "martelo"   , dict = "amb@world_human_hammering@male@base"               , anim = "base"                          , prop = "prop_tool_hammer"     , flag = 49 , hand = 28422 },
    { nome = "pescar"    , dict = "amb@world_human_stand_fishing@base"                , anim = "base"                          , prop = "prop_fishing_rod_01"  , flag = 49 , hand = 60309 },
    { nome = "pescar2"   , dict = "amb@world_human_stand_fishing@idle_a"              , anim = "idle_c"                        , prop = "prop_fishing_rod_01"  , flag = 49 , hand = 60309 },
    { nome = "soprador"  , dict = "amb@code_human_wander_gardener_leaf_blower@base"   , anim = "static"                        , prop = "prop_leaf_blower_01"  , flag = 49 , hand = 28422 },
    { nome = "soprador2" , dict = "amb@code_human_wander_gardener_leaf_blower@idle_a" , anim = "idle_a"                        , prop = "prop_leaf_blower_01"  , flag = 49 , hand = 28422 },
    { nome = "soprador3" , dict = "amb@code_human_wander_gardener_leaf_blower@idle_a" , anim = "idle_b"                        , prop = "prop_leaf_blower_01"  , flag = 49 , hand = 28422 },
    { nome = "selfie"    , dict = "cellphone@self"                                    , anim = "selfie_in_from_text"           , prop = "prop_amb_phone"       , flag = 50 , hand = 28422 },
    { nome = "selfie2"   , dict = "cellphone@"                                        , anim = "cellphone_text_read_base_cover_low", prop = "prop_amb_phone"   , flag = 50 , hand = 28422 },
    { nome = "binoculos" , dict = "amb@world_human_binoculars@male@enter"             , anim = "enter"                         , prop = "prop_binoc_01"        , flag = 50 , hand = 28422 },

    -- ANIMAÇÕES PURAS
    { nome = "verificar"   , dict = "amb@medic@standing@tendtodead@idle_a"              , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "mexer"       , dict = "amb@prop_human_parking_meter@female@idle_a"        , anim = "idle_a_female"                   , loop = true  , andar = true  },
    { nome = "cuidar"      , dict = "mini@cpr@char_a@cpr_str"                           , anim = "cpr_pumpchest"                   , loop = true  , andar = true  },
    { nome = "cuidar2"     , dict = "mini@cpr@char_a@cpr_str"                           , anim = "cpr_kol"                         , loop = true  , andar = true  },
    { nome = "cuidar3"     , dict = "mini@cpr@char_a@cpr_str"                           , anim = "cpr_kol_idle"                    , loop = true  , andar = true  },
    { nome = "cansado"     , dict = "rcmbarry"                                          , anim = "idle_d"                          , loop = true  , andar = false },
    { nome = "alongar2"    , dict = "mini@triathlon"                                    , anim = "idle_e"                          , loop = true  , andar = false },
    { nome = "meleca"      , dict = "anim@mp_player_intuppernose_pick"                  , anim = "idle_a"                          , loop = true  , andar = true  },
    { nome = "bora"        , dict = "missfam4"                                          , anim = "say_hurry_up_a_trevor"           , loop = false , andar = true  },
    { nome = "limpar"      , dict = "missfbi3_camcrew"                                  , anim = "final_loop_guy"                  , loop = false , andar = true  },
    { nome = "galinha"     , dict = "random@peyote@chicken"                             , anim = "wakeup"                          , loop = true  , andar = true  },
    { nome = "amem"        , dict = "rcmepsilonism8"                                    , anim = "worship_base"                    , loop = true  , andar = true  },
    { nome = "nervoso"     , dict = "rcmme_tracey1"                                     , anim = "nervous_loop"                    , loop = true  , andar = true  },
    { nome = "morrer"      , dict = "misslamar1dead_body"                               , anim = "dead_idle"                       , loop = true  , andar = false },
    { nome = "ajoelhar"    , dict = "amb@medic@standing@kneel@idle_a"                   , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "abanar"      , dict = "timetable@amanda@facemask@base"                    , anim = "base"                            , loop = true  , andar = true  },
    { nome = "cocada"      , dict = "mp_player_int_upperarse_pick"                      , anim = "mp_player_int_arse_pick"         , loop = true  , andar = true  },
    { nome = "cocada2"     , dict = "mp_player_int_uppergrab_crotch"                    , anim = "mp_player_int_grab_crotch"       , loop = true  , andar = true  },
    { nome = "lero"        , dict = "anim@mp_player_intselfiejazz_hands"                , anim = "idle_a"                          , loop = false , andar = true  },
    { nome = "dj2"         , dict = "anim@mp_player_intupperair_synth"                  , anim = "idle_a_fp"                       , loop = true  , andar = false },
    { nome = "beijo"       , dict = "anim@mp_player_intselfieblow_kiss"                 , anim = "exit"                            , loop = false , andar = true  },
    { nome = "malicia"     , dict = "anim@mp_player_intupperdock"                       , anim = "idle_a"                          , loop = false , andar = true  },
    { nome = "digitar"     , dict = "anim@heists@prison_heistig1_p1_guard_checks_bus"   , anim = "loop"                            , loop = true  , andar = false },
    { nome = "continencia" , dict = "mp_player_int_uppersalute"                         , anim = "mp_player_int_salute"            , loop = true  , andar = true  },
    { nome = "atm"         , dict = "amb@prop_human_atm@male@idle_a"                    , anim = "idle_a"                          , loop = false , andar = false },
    { nome = "no"          , dict = "mp_player_int_upper_nod"                           , anim = "mp_player_int_nod_no"            , loop = true  , andar = true  },
    { nome = "palmas"      , dict = "anim@mp_player_intcelebrationfemale@slow_clap"     , anim = "slow_clap"                       , loop = false , andar = true  },
    { nome = "palmas2"     , dict = "amb@world_human_cheering@male_b"                   , anim = "base"                            , loop = true  , andar = true  },
    { nome = "palmas3"     , dict = "amb@world_human_cheering@male_d"                   , anim = "base"                            , loop = true  , andar = true  },
    { nome = "palmas4"     , dict = "amb@world_human_cheering@male_e"                   , anim = "base"                            , loop = true  , andar = true  },
    { nome = "palmas5"     , dict = "anim@arena@celeb@flat@solo@no_props@"              , anim = "angry_clap_a_player_a"           , loop = true  , andar = false },
    { nome = "palmas6"     , dict = "anim@mp_player_intupperslow_clap"                  , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "postura"     , dict = "anim@heists@prison_heiststation@cop_reactions"     , anim = "cop_a_idle"                      , loop = true  , andar = true  },
    { nome = "postura2"    , dict = "amb@world_human_cop_idles@female@base"             , anim = "base"                            , loop = true  , andar = true  },
    { nome = "peace"       , dict = "mp_player_int_upperpeace_sign"                     , anim = "mp_player_int_peace_sign"        , loop = true  , andar = true  },
    { nome = "deitar"      , dict = "amb@world_human_sunbathe@female@back@idle_a"       , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "deitar2"     , dict = "amb@world_human_sunbathe@female@front@idle_a"      , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "deitar3"     , dict = "amb@world_human_sunbathe@male@back@idle_a"         , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "deitar4"     , dict = "amb@world_human_sunbathe@male@front@idle_a"        , anim = "idle_a"                          , loop = true  , andar = false },
    { nome = "deitar5"     , dict = "mini@cpr@char_b@cpr_str"                           , anim = "cpr_kol_idle"                    , loop = true  , andar = false },
    { nome = "deitar6"     , dict = "switch@trevor@scares_tramp"                        , anim = "trev_scares_tramp_idle_tramp"    , loop = true  , andar = false },
    { nome = "deitar7"     , dict = "switch@trevor@annoys_sunbathers"                   , anim = "trev_annoys_sunbathers_loop_girl", loop = true  , andar = false },
    { nome = "deitar8"     , dict = "switch@trevor@annoys_sunbathers"                   , anim = "trev_annoys_sunbathers_loop_guy" , loop = true  , andar = false },
    { nome = "debrucar"    , dict = "amb@prop_human_bum_shopping_cart@male@base"        , anim = "base"                            , loop = true  , andar = false },
    { nome = "dancar"      , dict = "rcmnigel1bnmt_1b"                                  , anim = "dance_loop_tyler"                , loop = true  , andar = false },
    { nome = "dancar2"     , dict = "mp_safehouse"                                      , anim = "lap_dance_girl"                  , loop = true  , andar = false },
    { nome = "dancar3"     , dict = "misschinese2_crystalmazemcs1_cs"                   , anim = "dance_loop_tao"                  , loop = true  , andar = false },
    { nome = "dancar4"     , dict = "mini@strip_club@private_dance@part1"               , anim = "priv_dance_p1"                   , loop = true  , andar = false },
    { nome = "dancar5"     , dict = "mini@strip_club@private_dance@part2"               , anim = "priv_dance_p2"                   , loop = true  , andar = false },
    { nome = "dancar6"     , dict = "mini@strip_club@private_dance@part3"               , anim = "priv_dance_p3"                   , loop = true  , andar = false },
    { nome = "dancar7"     , dict = "special_ped@mountain_dancer@monologue_2@monologue_2a", anim = "mnt_dnc_angel"                 , loop = true  , andar = false },
    { nome = "dancar8"     , dict = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag"               , loop = true  , andar = false },
    { nome = "dancar9"     , dict = "missfbi3_sniping"                                  , anim = "dance_m_default"                 , loop = true  , andar = false },

    -- DANÇAS NIGHTCLUB facedj@hi_intensity (dancar10–dancar178)
    { nome = "dancar10"  , dict = "anim@amb@nightclub@dancers@black_madonna_entourage@"          , anim = "hi_dance_facedj_09_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar11"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^1"   , loop = true , andar = false },
    { nome = "dancar12"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^2"   , loop = true , andar = false },
    { nome = "dancar13"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^3"   , loop = true , andar = false },
    { nome = "dancar14"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^4"   , loop = true , andar = false },
    { nome = "dancar15"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^5"   , loop = true , andar = false },
    { nome = "dancar16"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_female^6"   , loop = true , andar = false },
    { nome = "dancar17"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^1"     , loop = true , andar = false },
    { nome = "dancar18"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^2"     , loop = true , andar = false },
    { nome = "dancar19"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^3"     , loop = true , andar = false },
    { nome = "dancar20"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^4"     , loop = true , andar = false },
    { nome = "dancar21"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^5"     , loop = true , andar = false },
    { nome = "dancar22"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v1_male^6"     , loop = true , andar = false },
    { nome = "dancar23"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^1"   , loop = true , andar = false },
    { nome = "dancar24"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^2"   , loop = true , andar = false },
    { nome = "dancar25"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^3"   , loop = true , andar = false },
    { nome = "dancar26"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^4"   , loop = true , andar = false },
    { nome = "dancar27"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^5"   , loop = true , andar = false },
    { nome = "dancar28"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_female^6"   , loop = true , andar = false },
    { nome = "dancar29"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^1"     , loop = true , andar = false },
    { nome = "dancar30"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^2"     , loop = true , andar = false },
    { nome = "dancar31"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^3"     , loop = true , andar = false },
    { nome = "dancar32"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^4"     , loop = true , andar = false },
    { nome = "dancar33"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar34"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_09_v2_male^6"     , loop = true , andar = false },
    { nome = "dancar35"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^1"   , loop = true , andar = false },
    { nome = "dancar36"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^2"   , loop = true , andar = false },
    { nome = "dancar37"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^3"   , loop = true , andar = false },
    { nome = "dancar38"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^4"   , loop = true , andar = false },
    { nome = "dancar39"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^5"   , loop = true , andar = false },
    { nome = "dancar40"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_female^6"   , loop = true , andar = false },
    { nome = "dancar41"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^1"     , loop = true , andar = false },
    { nome = "dancar42"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^2"     , loop = true , andar = false },
    { nome = "dancar43"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^3"     , loop = true , andar = false },
    { nome = "dancar44"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^4"     , loop = true , andar = false },
    { nome = "dancar45"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^5"     , loop = true , andar = false },
    { nome = "dancar46"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v1_male^6"     , loop = true , andar = false },
    { nome = "dancar47"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^1"   , loop = true , andar = false },
    { nome = "dancar48"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^2"   , loop = true , andar = false },
    { nome = "dancar49"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^3"   , loop = true , andar = false },
    { nome = "dancar50"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^4"   , loop = true , andar = false },
    { nome = "dancar51"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^5"   , loop = true , andar = false },
    { nome = "dancar52"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_female^6"   , loop = true , andar = false },
    { nome = "dancar53"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^1"     , loop = true , andar = false },
    { nome = "dancar54"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^2"     , loop = true , andar = false },
    { nome = "dancar55"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^3"     , loop = true , andar = false },
    { nome = "dancar56"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^4"     , loop = true , andar = false },
    { nome = "dancar57"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar58"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_11_v2_male^6"     , loop = true , andar = false },
    { nome = "dancar59"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^1"   , loop = true , andar = false },
    { nome = "dancar60"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^2"   , loop = true , andar = false },
    { nome = "dancar61"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^3"   , loop = true , andar = false },
    { nome = "dancar62"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^4"   , loop = true , andar = false },
    { nome = "dancar63"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^5"   , loop = true , andar = false },
    { nome = "dancar64"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_female^6"   , loop = true , andar = false },
    { nome = "dancar65"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^1"     , loop = true , andar = false },
    { nome = "dancar66"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^2"     , loop = true , andar = false },
    { nome = "dancar67"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^3"     , loop = true , andar = false },
    { nome = "dancar68"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^4"     , loop = true , andar = false },
    { nome = "dancar69"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^5"     , loop = true , andar = false },
    { nome = "dancar70"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v1_male^6"     , loop = true , andar = false },
    { nome = "dancar71"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^1"   , loop = true , andar = false },
    { nome = "dancar72"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^2"   , loop = true , andar = false },
    { nome = "dancar73"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^3"   , loop = true , andar = false },
    { nome = "dancar74"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^4"   , loop = true , andar = false },
    { nome = "dancar75"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^5"   , loop = true , andar = false },
    { nome = "dancar76"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_female^6"   , loop = true , andar = false },
    { nome = "dancar77"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^1"     , loop = true , andar = false },
    { nome = "dancar78"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^2"     , loop = true , andar = false },
    { nome = "dancar79"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^3"     , loop = true , andar = false },
    { nome = "dancar80"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^4"     , loop = true , andar = false },
    { nome = "dancar81"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar82"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_13_v2_male^6"     , loop = true , andar = false },
    { nome = "dancar83"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^1"   , loop = true , andar = false },
    { nome = "dancar84"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^2"   , loop = true , andar = false },
    { nome = "dancar85"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^3"   , loop = true , andar = false },
    { nome = "dancar86"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^4"   , loop = true , andar = false },
    { nome = "dancar87"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^5"   , loop = true , andar = false },
    { nome = "dancar88"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_female^6"   , loop = true , andar = false },
    { nome = "dancar89"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^1"     , loop = true , andar = false },
    { nome = "dancar90"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^2"     , loop = true , andar = false },
    { nome = "dancar91"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^3"     , loop = true , andar = false },
    { nome = "dancar92"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^4"     , loop = true , andar = false },
    { nome = "dancar93"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^5"     , loop = true , andar = false },
    { nome = "dancar94"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v1_male^6"     , loop = true , andar = false },
    { nome = "dancar95"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^1"   , loop = true , andar = false },
    { nome = "dancar96"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^2"   , loop = true , andar = false },
    { nome = "dancar97"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^3"   , loop = true , andar = false },
    { nome = "dancar98"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^4"   , loop = true , andar = false },
    { nome = "dancar99"  , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^5"   , loop = true , andar = false },
    { nome = "dancar100" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_female^6"   , loop = true , andar = false },
    { nome = "dancar101" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^1"     , loop = true , andar = false },
    { nome = "dancar102" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^2"     , loop = true , andar = false },
    { nome = "dancar103" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^3"     , loop = true , andar = false },
    { nome = "dancar104" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^4"     , loop = true , andar = false },
    { nome = "dancar105" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar106" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_15_v2_male^6"     , loop = true , andar = false },
    { nome = "dancar107" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^1"   , loop = true , andar = false },
    { nome = "dancar108" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^2"   , loop = true , andar = false },
    { nome = "dancar109" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^3"   , loop = true , andar = false },
    { nome = "dancar110" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^4"   , loop = true , andar = false },
    { nome = "dancar111" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^5"   , loop = true , andar = false },
    { nome = "dancar112" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_female^6"   , loop = true , andar = false },
    { nome = "dancar113" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^1"     , loop = true , andar = false },
    { nome = "dancar114" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^2"     , loop = true , andar = false },
    { nome = "dancar115" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^3"     , loop = true , andar = false },
    { nome = "dancar116" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^4"     , loop = true , andar = false },
    { nome = "dancar117" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^5"     , loop = true , andar = false },
    { nome = "dancar118" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v1_male^6"     , loop = true , andar = false },
    { nome = "dancar119" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^1"   , loop = true , andar = false },
    { nome = "dancar120" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^2"   , loop = true , andar = false },
    { nome = "dancar121" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^3"   , loop = true , andar = false },
    { nome = "dancar122" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^4"   , loop = true , andar = false },
    { nome = "dancar123" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^5"   , loop = true , andar = false },
    { nome = "dancar124" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_female^6"   , loop = true , andar = false },
    { nome = "dancar125" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^1"     , loop = true , andar = false },
    { nome = "dancar126" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^2"     , loop = true , andar = false },
    { nome = "dancar127" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^3"     , loop = true , andar = false },
    { nome = "dancar128" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^4"     , loop = true , andar = false },
    { nome = "dancar129" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^5"     , loop = true , andar = false },
    { nome = "dancar130" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"    , anim = "hi_dance_facedj_17_v2_male^6"     , loop = true , andar = false },
    { nome = "dancar131" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar132" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^2"    , loop = true , andar = false },
    { nome = "dancar133" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^3"    , loop = true , andar = false },
    { nome = "dancar134" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^4"    , loop = true , andar = false },
    { nome = "dancar135" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^5"    , loop = true , andar = false },
    { nome = "dancar136" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_female^6"    , loop = true , andar = false },
    { nome = "dancar137" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^1"      , loop = true , andar = false },
    { nome = "dancar138" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^2"      , loop = true , andar = false },
    { nome = "dancar139" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^3"      , loop = true , andar = false },
    { nome = "dancar140" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^4"      , loop = true , andar = false },
    { nome = "dancar141" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^5"      , loop = true , andar = false },
    { nome = "dancar142" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v1_male^6"      , loop = true , andar = false },
    { nome = "dancar143" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^1"    , loop = true , andar = false },
    { nome = "dancar144" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^2"    , loop = true , andar = false },
    { nome = "dancar145" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^3"    , loop = true , andar = false },
    { nome = "dancar146" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^4"    , loop = true , andar = false },
    { nome = "dancar147" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^5"    , loop = true , andar = false },
    { nome = "dancar148" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_female^6"    , loop = true , andar = false },
    { nome = "dancar149" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^1"      , loop = true , andar = false },
    { nome = "dancar150" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^2"      , loop = true , andar = false },
    { nome = "dancar151" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^3"      , loop = true , andar = false },
    { nome = "dancar152" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^4"      , loop = true , andar = false },
    { nome = "dancar153" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^5"      , loop = true , andar = false },
    { nome = "dancar154" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_09_v2_male^6"      , loop = true , andar = false },
    { nome = "dancar155" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar156" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^2"    , loop = true , andar = false },
    { nome = "dancar157" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^3"    , loop = true , andar = false },
    { nome = "dancar158" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^4"    , loop = true , andar = false },
    { nome = "dancar159" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^5"    , loop = true , andar = false },
    { nome = "dancar160" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_female^6"    , loop = true , andar = false },
    { nome = "dancar161" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^1"      , loop = true , andar = false },
    { nome = "dancar162" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^2"      , loop = true , andar = false },
    { nome = "dancar163" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^3"      , loop = true , andar = false },
    { nome = "dancar164" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^4"      , loop = true , andar = false },
    { nome = "dancar165" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^5"      , loop = true , andar = false },
    { nome = "dancar166" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_11_v1_male^6"      , loop = true , andar = false },
    { nome = "dancar167" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar168" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^2"    , loop = true , andar = false },
    { nome = "dancar169" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^3"    , loop = true , andar = false },
    { nome = "dancar170" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^4"    , loop = true , andar = false },
    { nome = "dancar171" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^5"    , loop = true , andar = false },
    { nome = "dancar172" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_female^6"    , loop = true , andar = false },
    { nome = "dancar173" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_male^1"      , loop = true , andar = false },
    { nome = "dancar174" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_male^2"      , loop = true , andar = false },
    { nome = "dancar175" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_male^3"      , loop = true , andar = false },
    { nome = "dancar176" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v1_male^4"      , loop = true , andar = false },
    { nome = "dancar177" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v2_male^5"      , loop = true , andar = false },
    { nome = "dancar178" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_13_v2_male^6"      , loop = true , andar = false },
    { nome = "dancar179" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar180" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^2"    , loop = true , andar = false },
    { nome = "dancar181" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^3"    , loop = true , andar = false },
    { nome = "dancar182" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^4"    , loop = true , andar = false },
    { nome = "dancar183" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^5"    , loop = true , andar = false },
    { nome = "dancar184" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_female^6"    , loop = true , andar = false },
    { nome = "dancar185" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^1"      , loop = true , andar = false },
    { nome = "dancar186" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^2"      , loop = true , andar = false },
    { nome = "dancar187" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^3"      , loop = true , andar = false },
    { nome = "dancar188" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^4"      , loop = true , andar = false },
    { nome = "dancar189" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^5"      , loop = true , andar = false },
    { nome = "dancar190" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v1_male^6"      , loop = true , andar = false },
    { nome = "dancar191" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^1"    , loop = true , andar = false },
    { nome = "dancar192" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^2"    , loop = true , andar = false },
    { nome = "dancar193" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^3"    , loop = true , andar = false },
    { nome = "dancar194" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^4"    , loop = true , andar = false },
    { nome = "dancar195" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^5"    , loop = true , andar = false },
    { nome = "dancar196" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_female^6"    , loop = true , andar = false },
    { nome = "dancar197" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^1"      , loop = true , andar = false },
    { nome = "dancar198" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^2"      , loop = true , andar = false },
    { nome = "dancar199" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^3"      , loop = true , andar = false },
    { nome = "dancar200" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^4"      , loop = true , andar = false },
    { nome = "dancar201" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^5"      , loop = true , andar = false },
    { nome = "dancar202" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_15_v2_male^6"      , loop = true , andar = false },
    { nome = "dancar203" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar204" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^2"    , loop = true , andar = false },
    { nome = "dancar205" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^3"    , loop = true , andar = false },
    { nome = "dancar206" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^4"    , loop = true , andar = false },
    { nome = "dancar207" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^5"    , loop = true , andar = false },
    { nome = "dancar208" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_female^6"    , loop = true , andar = false },
    { nome = "dancar209" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^1"      , loop = true , andar = false },
    { nome = "dancar210" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^2"      , loop = true , andar = false },
    { nome = "dancar211" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^3"      , loop = true , andar = false },
    { nome = "dancar212" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^4"      , loop = true , andar = false },
    { nome = "dancar213" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^5"      , loop = true , andar = false },
    { nome = "dancar214" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v1_male^6"      , loop = true , andar = false },
    { nome = "dancar215" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^1"    , loop = true , andar = false },
    { nome = "dancar216" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^2"    , loop = true , andar = false },
    { nome = "dancar217" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^3"    , loop = true , andar = false },
    { nome = "dancar218" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^4"    , loop = true , andar = false },
    { nome = "dancar219" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^5"    , loop = true , andar = false },
    { nome = "dancar220" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_female^6"    , loop = true , andar = false },
    { nome = "dancar221" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^1"      , loop = true , andar = false },
    { nome = "dancar222" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^2"      , loop = true , andar = false },
    { nome = "dancar223" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^3"      , loop = true , andar = false },
    { nome = "dancar224" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^4"      , loop = true , andar = false },
    { nome = "dancar225" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^5"      , loop = true , andar = false },
    { nome = "dancar226" , dict = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity"    , anim = "hi_dance_crowd_17_v2_male^6"      , loop = true , andar = false },
    { nome = "dancar227" , dict = "anim@mp_player_intcelebrationfemale@the_woogie"               , anim = "the_woogie"                        , loop = true , andar = false },
    { nome = "dancar228" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@"        , anim = "med_center_up"                     , loop = true , andar = false },
    { nome = "dancar229" , dict = "anim@amb@casino@mini@dance@dance_solo@female@var_b@"           , anim = "high_center"                       , loop = true , andar = false },
    { nome = "dancar230" , dict = "timetable@tracy@ig_8@idle_b"                                   , anim = "idle_d"                            , loop = true , andar = false },
    { nome = "dancar231" , dict = "timetable@tracy@ig_5@idle_a"                                   , anim = "idle_a"                            , loop = true , andar = false },
    { nome = "dancar232" , dict = "anim@amb@nightclub@lazlow@hi_podium@"                          , anim = "danceidle_hi_11_buttwiggle_b_laz"  , loop = true , andar = false },
    { nome = "dancar233" , dict = "move_clown@p_m_two_idles@"                                     , anim = "fidget_short_dance"                , loop = true , andar = false },
    { nome = "dancar234" , dict = "move_clown@p_m_zero_idles@"                                    , anim = "fidget_short_dance"                , loop = true , andar = false },
    { nome = "dancar235" , dict = "misschinese2_crystalmazemcs1_ig"                               , anim = "dance_loop_tao"                    , loop = true , andar = false },
    { nome = "dancar236" , dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@"           , anim = "low_center"                        , loop = true , andar = false },
    { nome = "dancar237" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@"         , anim = "low_center_down"                   , loop = true , andar = false },
    { nome = "dancar238" , dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@"           , anim = "low_center"                        , loop = true , andar = false },
    { nome = "dancar239" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@"         , anim = "high_center_up"                    , loop = true , andar = false },
    { nome = "dancar240" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@"         , anim = "high_center"                       , loop = true , andar = true  },
    { nome = "dancar241" , dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@"           , anim = "high_center_up"                    , loop = true , andar = false },
    { nome = "dancar242" , dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@"           , anim = "high_center"                       , loop = true , andar = false },
    { nome = "dancar243" , dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@"           , anim = "high_center_down"                  , loop = true , andar = false },
    { nome = "dancar244" , dict = "anim@amb@nightclub@dancers@podium_dancers@"                    , anim = "hi_dance_facedj_17_v2_male^5"      , loop = true , andar = false },
    { nome = "dancar245" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@"         , anim = "low_center"                        , loop = true , andar = false },
    { nome = "dancar246" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@"         , anim = "low_center_down"                   , loop = true , andar = false },
    { nome = "dancar247" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@"         , anim = "low_center"                        , loop = true , andar = false },
    { nome = "dancar248" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@"         , anim = "high_center_up"                    , loop = true , andar = false },
    { nome = "dancar249" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"      , anim = "hi_dance_facedj_09_v2_female^3"    , loop = true , andar = false },
    { nome = "dancar250" , dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity"      , anim = "hi_dance_facedj_09_v2_female^1"    , loop = true , andar = false },
    { nome = "dancar251" , dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@"         , anim = "high_center"                       , loop = true , andar = false },
    { nome = "dancar252" , dict = "anim@amb@nightclub@dancers@solomun_entourage@"                 , anim = "mi_dance_facedj_17_v1_female^1"    , loop = true , andar = false },
    { nome = "dancar253" , dict = "anim@amb@casino@mini@dance@dance_solo@female@var_a@"            , anim = "med_center"                        , loop = true , andar = false },

    -- ADULTO (sem veículo)
    { nome = "sexo"  , dict = "rcmpaparazzo_2"                                          , anim = "shag_loop_poppy"          , loop = true  , andar = false },
    { nome = "sexo2" , dict = "rcmpaparazzo_2"                                          , anim = "shag_loop_a"              , loop = true  , andar = false },
    { nome = "sexo3" , dict = "anim@mp_player_intcelebrationfemale@air_shagging"        , anim = "air_shagging"             , loop = true  , andar = false },

    -- ADULTO (requer veículo)
    { nome = "sexo4" , dict = "oddjobs@towing"           , anim = "m_blow_job_loop"              , loop = true , andar = false , carros = true },
    { nome = "sexo5" , dict = "oddjobs@towing"           , anim = "f_blow_job_loop"              , loop = true , andar = false , carros = true },
    { nome = "sexo6" , dict = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_female"    , loop = true , andar = false , carros = true },

    -- SENTAR
    { nome = "sentar2"  , dict = "amb@world_human_picnic@male@base"                     , anim = "base"                        , loop = true , andar = false },
    { nome = "sentar3"  , dict = "anim@heists@fleeca_bank@ig_7_jetski_owner"            , anim = "owner_idle"                  , loop = true , andar = false },
    { nome = "sentar4"  , dict = "amb@world_human_stupor@male@base"                     , anim = "base"                        , loop = true , andar = false },
    { nome = "sentar5"  , dict = "amb@world_human_picnic@female@base"                   , anim = "base"                        , loop = true , andar = false },
    { nome = "sentar6"  , dict = "anim@amb@nightclub@lazlow@lo_alone@"                  , anim = "lowalone_base_laz"           , loop = true , andar = false },
    { nome = "sentar7"  , dict = "anim@amb@business@bgen@bgen_no_work@"                 , anim = "sit_phone_phoneputdown_idle_nowork", loop = true , andar = false },
    { nome = "sentar8"  , dict = "rcm_barry3"                                           , anim = "barry_3_sit_loop"            , loop = true , andar = false },
    { nome = "sentar9"  , dict = "amb@world_human_picnic@male@idle_a"                   , anim = "idle_a"                      , loop = true , andar = false },
    { nome = "sentar10" , dict = "amb@world_human_picnic@female@idle_a"                 , anim = "idle_a"                      , loop = true , andar = false },
    { nome = "sentar11" , dict = "timetable@jimmy@mics3_ig_15@"                         , anim = "idle_a_jimmy"                , loop = true , andar = false },
    { nome = "sentar12" , dict = "timetable@jimmy@mics3_ig_15@"                         , anim = "mics3_15_base_jimmy"         , loop = true , andar = false },
    { nome = "sentar13" , dict = "amb@world_human_stupor@male@idle_a"                   , anim = "idle_a"                      , loop = true , andar = false },
    { nome = "sentar14" , dict = "timetable@tracy@ig_14@"                               , anim = "ig_14_base_tracy"            , loop = true , andar = false },
    { nome = "sentar15" , dict = "anim@heists@ornate_bank@hostages@hit"                 , anim = "hit_loop_ped_b"              , loop = true , andar = false },
    { nome = "sentar16" , dict = "anim@heists@ornate_bank@hostages@ped_e@"              , anim = "flinch_loop"                 , loop = true , andar = false },
    { nome = "sentar17" , dict = "timetable@ron@ig_5_p3"                                , anim = "ig_5_p3_base"                , loop = true , andar = false },
    { nome = "sentar18" , dict = "timetable@reunited@ig_10"                             , anim = "base_amanda"                 , loop = true , andar = false },
    { nome = "sentar19" , dict = "timetable@ron@ig_3_couch"                             , anim = "base"                        , loop = true , andar = false },
    { nome = "sentar20" , dict = "timetable@jimmy@mics3_ig_15@"                         , anim = "mics3_15_base_tracy"         , loop = true , andar = false },
    { nome = "sentar21" , dict = "timetable@maid@couch@"                                , anim = "base"                        , loop = true , andar = false },
    { nome = "sentar22" , dict = "timetable@ron@ron_ig_2_alt1"                          , anim = "ig_2_alt1_base"              , loop = true , andar = false },

    -- INTERAÇÃO / SOCIAL
    { nome = "beijar"      , dict = "mp_ped_interaction"                                    , anim = "kisses_guy_a"                , loop = false , andar = false },
    { nome = "abracar"     , dict = "mp_ped_interaction"                                    , anim = "hugs_guy_a"                  , loop = false , andar = false },
    { nome = "abracar2"    , dict = "mp_ped_interaction"                                    , anim = "kisses_guy_b"                , loop = false , andar = false },
    { nome = "striper"     , dict = "mini@strip_club@idles@stripper"                        , anim = "stripper_idle_02"            , loop = true  , andar = false },
    { nome = "escutar"     , dict = "mini@safe_cracking"                                    , anim = "idle_base"                   , loop = true  , andar = false },
    { nome = "alongar"     , dict = "anim@deathmatch_intros@unarmed"                        , anim = "intro_male_unarmed_e"        , loop = true  , andar = false },
    { nome = "dj"          , dict = "anim@mp_player_intupperdj"                             , anim = "idle_a"                      , loop = true  , andar = true  },
    { nome = "rock"        , dict = "anim@mp_player_intcelebrationmale@air_guitar"          , anim = "air_guitar"                  , loop = true  , andar = false },
    { nome = "rock2"       , dict = "mp_player_introck"                                     , anim = "mp_player_int_rock"          , loop = false , andar = false },
    { nome = "peitos"      , dict = "mini@strip_club@backroom@"                             , anim = "stripper_b_backroom_idle_b"  , loop = false , andar = false },
    { nome = "espernear"   , dict = "missfam4leadinoutmcs2"                                 , anim = "tracy_loop"                  , loop = true  , andar = false },
    { nome = "arrumar"     , dict = "anim@amb@business@coc@coc_packing_hi@"                 , anim = "full_cycle_v1_pressoperator" , loop = true  , andar = false },
    { nome = "coca"        , dict = "anim@amb@business@coc@coc_packing_hi@"                 , anim = "full_cycle_v3_pressoperator" , loop = true  , andar = false },
    { nome = "bebado"      , dict = "missfam5_blackout"                                     , anim = "pass_out"                    , loop = false , andar = false },
    { nome = "bebado2"     , dict = "missheist_agency3astumble_getup"                       , anim = "stumble_getup"               , loop = false , andar = false },
    { nome = "bebado3"     , dict = "missfam5_blackout"                                     , anim = "vomit"                       , loop = false , andar = false },
    { nome = "bebado4"     , dict = "random@drunk_driver_1"                                 , anim = "drunk_fall_over"             , loop = false , andar = false },
    { nome = "bebado5"     , dict = "misscarsteal4@actor"                                   , anim = "stumble"                     , loop = false , andar = false },
    { nome = "yoga"        , dict = "missfam5_yoga"                                         , anim = "f_yogapose_a"                , loop = true  , andar = false },
    { nome = "yoga2"       , dict = "amb@world_human_yoga@male@base"                        , anim = "base_a"                      , loop = true  , andar = false },
    { nome = "abdominal"   , dict = "amb@world_human_sit_ups@male@base"                     , anim = "base"                        , loop = true  , andar = false },
    { nome = "dormir"      , dict = "anim@heists@ornate_bank@hostages@hit"                  , anim = "hit_react_die_loop_ped_a"    , loop = true  , andar = false },
    { nome = "dormir2"     , dict = "anim@heists@ornate_bank@hostages@hit"                  , anim = "hit_react_die_loop_ped_e"    , loop = true  , andar = false },
    { nome = "dormir3"     , dict = "anim@heists@ornate_bank@hostages@hit"                  , anim = "hit_react_die_loop_ped_h"    , loop = true  , andar = false },
    { nome = "dormir4"     , dict = "mp_sleep"                                              , anim = "sleep_loop"                  , loop = true  , andar = false },
    { nome = "dormir5"     , dict = "missarmenian2"                                         , anim = "drunk_loop"                  , loop = true  , andar = false },
    { nome = "encostar"    , dict = "amb@lo_res_idles@"                                     , anim = "world_human_lean_male_foot_up_lo_res_base", loop = true , andar = false },
    { nome = "estatua"     , dict = "amb@world_human_statue@base"                           , anim = "base"                        , loop = true  , andar = false },
    { nome = "flexao"      , dict = "amb@world_human_push_ups@male@base"                    , anim = "base"                        , loop = true  , andar = false },
    { nome = "malhar2"     , dict = "amb@prop_human_muscle_chin_ups@male@base"              , anim = "base"                        , loop = true  , andar = false },
    { nome = "plantar"     , dict = "amb@world_human_gardener_plant@female@base"            , anim = "base_female"                 , loop = true  , andar = false },
    { nome = "plantar2"    , dict = "amb@world_human_gardener_plant@female@idle_a"          , anim = "idle_a_female"               , loop = true  , andar = false },
    { nome = "procurar"    , dict = "amb@world_human_bum_wash@male@high@base"               , anim = "base"                        , loop = true  , andar = false },
    { nome = "trotar"      , dict = "amb@world_human_jog_standing@male@fitidle_a"           , anim = "idle_a"                      , loop = true  , andar = false },
    { nome = "mecanico"    , dict = "amb@world_human_vehicle_mechanic@male@idle_a"          , anim = "idle_a"                      , loop = true  , andar = false },
    { nome = "mecanico2"   , dict = "mini@repair"                                           , anim = "fixing_a_player"             , loop = true  , andar = false },
    { nome = "mecanico3"   , dict = "mini@repair"                                           , anim = "fixing_a_ped"                , loop = true  , andar = false },
    { nome = "pullover"    , dict = "misscarsteal3pullover"                                  , anim = "pull_over_right"             , loop = false , andar = false },
    { nome = "airguitar"   , dict = "anim@mp_player_intcelebrationfemale@air_guitar"        , anim = "air_guitar"                  , loop = true  , andar = false },
    { nome = "airsynth"    , dict = "anim@mp_player_intcelebrationfemale@air_synth"         , anim = "air_synth"                   , loop = true  , andar = false },
    { nome = "puto"        , dict = "misscarsteal4@actor"                                   , anim = "actor_berating_loop"         , loop = true  , andar = true  },
    { nome = "puto2"       , dict = "oddjobs@assassinate@vice@hooker"                       , anim = "argue_a"                     , loop = true  , andar = true  },
    { nome = "puto3"       , dict = "mini@triathlon"                                        , anim = "want_some_of_this"           , loop = false , andar = false },
    { nome = "unhas"       , dict = "anim@amb@clubhouse@bar@drink@idle_a"                   , anim = "idle_a_bartender"            , loop = true  , andar = true  },
    { nome = "mandarbeijo" , dict = "anim@mp_player_intcelebrationfemale@blow_kiss"         , anim = "blow_kiss"                   , loop = false , andar = false },
    { nome = "mandarbeijo2", dict = "anim@mp_player_intselfieblow_kiss"                     , anim = "exit"                        , loop = false , andar = false },
    { nome = "bale"        , dict = "anim@mp_player_intcelebrationpaired@f_f_sarcastic"     , anim = "sarcastic_left"              , loop = true  , andar = false },
    { nome = "bonzao"      , dict = "misscommon@response"                                   , anim = "bring_it_on"                 , loop = false , andar = false },
    { nome = "cruzarbraco" , dict = "anim@amb@nightclub@peds@"                              , anim = "rcmme_amanda1_stand_loop_cop", loop = true  , andar = true  },
    { nome = "cruzarbraco2", dict = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim = "idle_a"                  , loop = true  , andar = true  },
    { nome = "wtf"         , dict = "anim@mp_player_intcelebrationfemale@face_palm"         , anim = "face_palm"                   , loop = false , andar = true  },
    { nome = "wtf2"        , dict = "random@car_thief@agitated@idle_a"                      , anim = "agitated_idle_a"             , loop = false , andar = true  },
    { nome = "wtf3"        , dict = "missminuteman_1ig_2"                                   , anim = "tasered_2"                   , loop = false , andar = true  },
    { nome = "wtf4"        , dict = "anim@mp_player_intupperface_palm"                      , anim = "idle_a"                      , loop = false , andar = true  },
    { nome = "suicidio"    , dict = "mp_suicide"                                            , anim = "pistol"                      , loop = false , andar = false },
    { nome = "suicidio2"   , dict = "mp_suicide"                                            , anim = "pill"                        , loop = false , andar = false },
    { nome = "lutar"       , dict = "anim@deathmatch_intros@unarmed"                        , anim = "intro_male_unarmed_c"        , loop = false , andar = false },
    { nome = "lutar2"      , dict = "anim@deathmatch_intros@unarmed"                        , anim = "intro_male_unarmed_e"        , loop = false , andar = false },
    { nome = "lutar3"      , dict = "rcmextreme2"                                           , anim = "loop_punching"               , loop = true  , andar = true  },
    { nome = "dedo"        , dict = "anim@mp_player_intselfiethe_bird"                      , anim = "idle_a"                      , loop = false , andar = false },
    { nome = "mochila"     , dict = "move_m@hiking"                                         , anim = "idle"                        , loop = true  , andar = true  },
    { nome = "exercicios"  , dict = "timetable@reunited@ig_2"                               , anim = "jimmy_getknocked"            , loop = true  , andar = true  },
    { nome = "escorar"     , dict = "timetable@mime@01_gc"                                  , anim = "idle_a"                      , loop = true  , andar = false },
    { nome = "escorar2"    , dict = "misscarstealfinale"                                    , anim = "packer_idle_1_trevor"        , loop = true  , andar = false },
    { nome = "escorar3"    , dict = "misscarstealfinalecar_5_ig_1"                          , anim = "waitloop_lamar"              , loop = true  , andar = false },
    { nome = "escorar4"    , dict = "rcmjosh2"                                              , anim = "josh_2_intp1_base"           , loop = true  , andar = false },
    { nome = "meditar"     , dict = "rcmcollect_paperleadinout@"                            , anim = "meditiate_idle"              , loop = true  , andar = false },
    { nome = "meditar2"    , dict = "rcmepsilonism3"                                        , anim = "ep_3_rcm_marnie_meditating"  , loop = true  , andar = false },
    { nome = "meditar3"    , dict = "rcmepsilonism3"                                        , anim = "base_loop"                   , loop = true  , andar = false },
    { nome = "meditar4"    , dict = "timetable@amanda@ig_4"                                 , anim = "ig_4_base"                   , loop = true  , andar = false },
    { nome = "meleca2"     , dict = "anim@mp_player_intcelebrationfemale@nose_pick"         , anim = "nose_pick"                   , loop = false , andar = false },
    { nome = "meleca3"     , dict = "move_p_m_two_idles@generic"                            , anim = "fidget_sniff_fingers"        , loop = false , andar = true  },
    { nome = "cortaessa"   , dict = "gestures@m@standing@casual"                            , anim = "gesture_no_way"              , loop = false , andar = false },
    { nome = "joia"        , dict = "anim@mp_player_intincarthumbs_uplow@ds@"               , anim = "enter"                       , loop = false , andar = false },
    { nome = "joia2"       , dict = "anim@mp_player_intselfiethumbs_up"                     , anim = "idle_a"                      , loop = false , andar = false },
    { nome = "yeah"        , dict = "anim@mp_player_intupperair_shagging"                   , anim = "idle_a"                      , loop = false , andar = false },
    { nome = "assobiar"    , dict = "taxi_hail"                                             , anim = "hail_taxi"                   , loop = false , andar = false },
    { nome = "carona"      , dict = "random@hitch_lift"                                     , anim = "idle_f"                      , loop = false , andar = true  },
    { nome = "estatua2"    , dict = "fra_0_int-1"                                           , anim = "cs_lamardavis_dual-1"        , loop = true  , andar = false },
    { nome = "estatua3"    , dict = "club_intro2-0"                                         , anim = "csb_englishdave_dual-0"      , loop = true  , andar = false },
    { nome = "colher"      , dict = "creatures@rottweiler@tricks@"                          , anim = "petting_franklin"            , loop = false , andar = false },
    { nome = "rastejar"    , dict = "move_injured_ground"                                   , anim = "front_loop"                  , loop = true  , andar = false },
    { nome = "pirueta"     , dict = "anim@arena@celeb@flat@solo@no_props@"                  , anim = "cap_a_player_a"              , loop = false , andar = false },
    { nome = "pirueta2"    , dict = "anim@arena@celeb@flat@solo@no_props@"                  , anim = "flip_a_player_a"             , loop = false , andar = false },
    { nome = "fodase"      , dict = "anim@arena@celeb@podium@no_prop@"                      , anim = "flip_off_a_1st"              , loop = false , andar = false },
    { nome = "taco"        , dict = "anim@arena@celeb@flat@solo@no_props@"                  , anim = "slugger_a_player_a"          , loop = false , andar = false },
    { nome = "onda"        , dict = "anim@mp_player_intupperfind_the_fish"                  , anim = "idle_a"                      , loop = true  , andar = false },
    { nome = "alongar3"    , dict = "mini@triathlon"                                        , anim = "idle_f"                      , loop = true  , andar = false },
    { nome = "alongar4"    , dict = "mini@triathlon"                                        , anim = "idle_d"                      , loop = true  , andar = false },
    { nome = "alongar5"    , dict = "rcmfanatic1maryann_stretchidle_b"                      , anim = "idle_e"                      , loop = true  , andar = false },
    { nome = "heroi"       , dict = "rcmbarry"                                              , anim = "base"                        , loop = true  , andar = true  },
    { nome = "boboalegre"  , dict = "rcm_barry2"                                            , anim = "clown_idle_0"                , loop = false , andar = false },
    { nome = "boboalegre2" , dict = "rcm_barry2"                                            , anim = "clown_idle_1"                , loop = false , andar = false },
    { nome = "boboalegre3" , dict = "rcm_barry2"                                            , anim = "clown_idle_2"                , loop = false , andar = false },
    { nome = "boboalegre4" , dict = "rcm_barry2"                                            , anim = "clown_idle_3"                , loop = false , andar = false },
    { nome = "passaro"     , dict = "random@peyote@bird"                                    , anim = "wakeup"                      , loop = false , andar = false },
    { nome = "cachorro"    , dict = "random@peyote@dog"                                     , anim = "wakeup"                      , loop = false , andar = false },
    { nome = "karate"      , dict = "anim@mp_player_intcelebrationfemale@karate_chops"      , anim = "karate_chops"                , loop = false , andar = false },
    { nome = "karate2"     , dict = "anim@mp_player_intcelebrationmale@karate_chops"        , anim = "karate_chops"                , loop = false , andar = false },
    { nome = "ameacar"     , dict = "anim@mp_player_intcelebrationmale@cut_throat"          , anim = "cut_throat"                  , loop = false , andar = false },
    { nome = "ameacar2"    , dict = "anim@mp_player_intcelebrationfemale@cut_throat"        , anim = "cut_throat"                  , loop = false , andar = false },
    { nome = "boxe"        , dict = "anim@mp_player_intcelebrationmale@shadow_boxing"       , anim = "shadow_boxing"               , loop = false , andar = false },
    { nome = "boxe2"       , dict = "anim@mp_player_intcelebrationfemale@shadow_boxing"     , anim = "shadow_boxing"               , loop = false , andar = false },
    { nome = "mamamia"     , dict = "anim@mp_player_intcelebrationmale@finger_kiss"         , anim = "finger_kiss"                 , loop = false , andar = true  },
    { nome = "louco"       , dict = "anim@mp_player_intincaryou_locobodhi@ds@"              , anim = "idle_a"                      , loop = true  , andar = true  },
    { nome = "xiu"         , dict = "anim@mp_player_intincarshushbodhi@ds@"                 , anim = "idle_a_fp"                   , loop = true  , andar = true  },
    { nome = "cruzar"      , dict = "amb@world_human_cop_idles@female@idle_b"               , anim = "idle_e"                      , loop = true  , andar = true  },

    -- SCENARIOS (sem dict — usa TaskStartScenarioInPlace)
    { nome = "bixa"       , anim = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS"  },
    { nome = "cerveja"    , anim = "WORLD_HUMAN_PARTYING"              },
    { nome = "churrasco"  , anim = "PROP_HUMAN_BBQ"                    },
    { nome = "consertar"  , anim = "WORLD_HUMAN_WELDING"               },
    { nome = "fumar"      , anim = "WORLD_HUMAN_SMOKING"               },
    { nome = "fumar2"     , anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS" },
    { nome = "fumar3"     , anim = "WORLD_HUMAN_AA_SMOKE"              },
    { nome = "fumar4"     , anim = "WORLD_HUMAN_SMOKING_POT"           },
    { nome = "tragar"     , anim = "WORLD_HUMAN_DRUG_DEALER"           },
    { nome = "esquentar"  , anim = "WORLD_HUMAN_STAND_FIRE"            },
}


-- ============================================================
-- CONVERSÃO PARA MAP (O(1) lookup por nome)
-- ============================================================

VHubAnimacao.Cfg.CATALOG = {}
for _, entry in ipairs(_raw) do
    if entry.nome and not VHubAnimacao.Cfg.CATALOG[entry.nome] then
        VHubAnimacao.Cfg.CATALOG[entry.nome] = entry
    end
end
_raw = nil
